version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.15.0
    hostname: envoy
    container_name: envoy
    ports: 
      - "9090:9090"
      - "9901:9901"
    volumes:
      - ./front-end/envoy.yaml:/etc/envoy/envoy.yaml