apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
spec:
  selector:
    matchLabels:
      app: recipe
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: recipe
    spec:
      hostNetwork: true
      containers:
        - name: recipe-be
          image: recipe/go-recipe:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080